### ISSUE TITLE
A Question About RAMiT: Reciprocal Attention Mixing Transformer for Lightweight Image Restoration

### ISSUE THREAD

**Issue by francqz31** [rami0205/NGramSwin#3]
@rami0205  Hello Mr. Choi 
I Really like the RAMiT paper And the fact that it achieves state-of-the-art performance on multiple lightweight IR tasks.

When can we expect the code release of RAMiT ?? I will be eagerly waiting for it !

Btw did you compare the low-light enhancement of RAMiT with the low-light enhancement of https://github.com/wyf0912/LLFlow ?

Thanks in advance.

**Comment by rami0205** [comment]
RAMiT codes are available now.
Thank you for waiting!
