### ISSUE TITLE
A question about de-normalization.

### ISSUE THREAD

**Issue by stella-von** [rami0205/NGramSwin#4]
Thank you for nice work!
Have you conducted any more experiments on de-normalization? Does de-normalization have a positive impact on training SwinIR?

**Comment by rami0205** [comment]
Thank for your question.

Unfortunately, I have not applied de-normalization on SwinIR-NG, due to the fair comparison issue.
The performances reported in our paper come from the results of SwinIR paper.
Therefore, I have tried to keep the settings as SwinIR.

Thank you.
