### ISSUE TITLE
Methods about calculating Multi-Adds

### ISSUE THREAD

**Issue by Synapsess** [rami0205/NGramSwin#5]
hi, thanks for your great works. I want to know how to get the results of Multi-Adds in paper? since I find many libraries about calculating MAdds get incorrect result about self-attention.There are also some problems about the MAdds result in paper of SwinIR, so i am a kind of confused now. Thanks for your help.

**Comment by rami0205** [comment]
I also experienced what you said, when calculating flops with the existing libraries.

So I calculated it by mannually writting the codes that compute flops.

Please refer to `flops` functions in `my_model.ngswin_model.win_attention.py` file of this repository.

If you have other questions about this issue, please let me know.

Thank you.

**Comment by Synapsess** [comment]
thanks for your quick reply, i have found the function calculating flops about self-attention you mentioned.  I think you're manually calculating the FLOPs for various modules and adding them up, which is exactly what I've been looking for.   very grateful for your help again.
