### ISSUE TITLE
where is baby.npy?

### ISSUE THREAD

**Issue by zhangyu13141** [rami0205/NGramSwin#6]

**Comment by rami0205** [comment]
Please see https://1drv.ms/f/s!AoUesdU_BVZrivlVY04u7WHcSapUWg?e=eBBVfd of the issue https://github.com/rami0205/NGramSwin/issues/2

baby.npy is in the `Set5/HR` folder.
The corresponding babyx2.npy, babyx3.npy, babyx4.npy are in the `Set5/LR_bicubic` folder.

You can also find the other files in other folders.

Thank you.
