### ISSUE TITLE
about image size

### ISSUE THREAD

**Issue by Polarisamoon** [rami0205/NGramSwin#7]
Thank you for your work. I would like to ask if this algorithm can be applied to Super-Resolution small images, for example, images with dimensions of 12*12 pixels?

**Comment by rami0205** [comment]
I am not sure because I have not run the case you said. But as shown in supplementary materials (Figs.K,L) of my paper, our algorithm somewhat works in 32x32 Cifar10 dataset. Therefore, if you well prepare LR input data and corresponding HR ground-truth images, I think it can work.

Thanks.
